### ISSUE TITLE
Limit allowed nr of scanned documents

### ISSUE THREAD

**Issue by dajanvulaj** [shirsh94/flutter_doc_scanner#31]
It would be perfect if we could limit the nr of scans.
In some cases only one scan is required.

**Comment by fundlybhanit** [comment]
This issue is fixed, you will get update once PR is merged.  https://github.com/shirsh94/flutter_doc_scanner/pull/33#issue-2765602524

**Comment by pritamgudekar** [comment]
@fundlybhanit this is still not working. Still its scanning multiple times.

FlutterDocScanner().getScanDocuments(page: 1) is not working or not limiting to scan the document to only 1.

Please suggest.

**Comment by fundlybhanit** [comment]
@pritamgudekar Just checked in my system. Its working. Can you clarify which device or emulator are you using? Also check recheck your code. Revert if found something.

**Comment by pritamgudekar** [comment]
@fundlybhanit Sure. I am using iPhone 12 Max (iOS: 18.1.1) for the development. Not using emulator. 

I checked the code but it is simple and as given in the example only.
-

**Comment by pritamgudekar** [comment]
@fundlybhanit Any chance to look for above device? Any specific version you would like to recommend? Currently I am using [0.0.15](https://pub.dev/packages/flutter_doc_scanner/versions/0.0.15)

**Comment by fundlybhanit** [comment]
@pritamgudekar As per my investigation, the code is only for Android. @shirsh94 Can help here.

**Comment by shirsh94** [comment]
@fundlybhanit Give me some time, I will update this as soon as possible.
